// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "gibsonsfuns_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// trans_probs1
Eigen::Matrix<stan::promote_args_t<double, double, double, double, double,                 stan::promote_args_t<double, double, double, double>>,-1,1> trans_probs1(const int& instate, const int& nstates, const double& s_ad, const double& s_ado, const double& s_juv, const double& p_mv_out, const double& p_mv_in, const int& succ, const std::vector<double>& p_breed, const double& p_rec, const double& p_bead, const double& p_succ, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_trans_probs1(SEXP instateSEXP, SEXP nstatesSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_mv_outSEXP, SEXP p_mv_inSEXP, SEXP succSEXP, SEXP p_breedSEXP, SEXP p_recSEXP, SEXP p_beadSEXP, SEXP p_succSEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type instate(instateSEXP);
    Rcpp::traits::input_parameter< const int& >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< const double& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const double& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const double& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_mv_out(p_mv_outSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_mv_in(p_mv_inSEXP);
    Rcpp::traits::input_parameter< const int& >::type succ(succSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_breed(p_breedSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_rec(p_recSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_bead(p_beadSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_succ(p_succSEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(trans_probs1(instate, nstates, s_ad, s_ado, s_juv, p_mv_out, p_mv_in, succ, p_breed, p_rec, p_bead, p_succ, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// obs_probs1
Eigen::Matrix<stan::promote_args_t<double, double, double, double, double>,1,-1> obs_probs1(const int& latstate, const int& n_obs_states, const std::vector<double>& p_obs, const double& p_detect_juv, const double& p_detect_dead, const double& p_female, const double& p_succ, const int& succ, const int& no_visit, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_obs_probs1(SEXP latstateSEXP, SEXP n_obs_statesSEXP, SEXP p_obsSEXP, SEXP p_detect_juvSEXP, SEXP p_detect_deadSEXP, SEXP p_femaleSEXP, SEXP p_succSEXP, SEXP succSEXP, SEXP no_visitSEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type latstate(latstateSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_obs_states(n_obs_statesSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_obs(p_obsSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_detect_juv(p_detect_juvSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_detect_dead(p_detect_deadSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_female(p_femaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_succ(p_succSEXP);
    Rcpp::traits::input_parameter< const int& >::type succ(succSEXP);
    Rcpp::traits::input_parameter< const int& >::type no_visit(no_visitSEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(obs_probs1(latstate, n_obs_states, p_obs, p_detect_juv, p_detect_dead, p_female, p_succ, succ, no_visit, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_one_indiv_rng
std::vector<int> states_one_indiv_rng(const int& N_STATES_L, const int& N_STATES_O, const int& MAX_T, const std::vector<int>& NO_VISIT, const int& sex, const int& first_cap, const int& first_state, const int& agefirst, const std::vector<int>& c_hist, const std::vector<int>& isalive, const std::vector<int>& b_success, const std::vector<std::vector<double>>& s_ad, const std::vector<double>& s_ado, const std::vector<double>& s_juv, const std::vector<double>& p_moveout, const std::vector<double>& p_movein, const std::vector<std::vector<double>>& p_breeding, const double& age_rec_scale, const double& age_rec_inflection, const double& age_br_scale, const double& age_br_inflection, const std::vector<double>& p_success, const int& ind, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_one_indiv_rng(SEXP N_STATES_LSEXP, SEXP N_STATES_OSEXP, SEXP MAX_TSEXP, SEXP NO_VISITSEXP, SEXP sexSEXP, SEXP first_capSEXP, SEXP first_stateSEXP, SEXP agefirstSEXP, SEXP c_histSEXP, SEXP isaliveSEXP, SEXP b_successSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_moveoutSEXP, SEXP p_moveinSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP indSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_O(N_STATES_OSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NO_VISIT(NO_VISITSEXP);
    Rcpp::traits::input_parameter< const int& >::type sex(sexSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_cap(first_capSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_state(first_stateSEXP);
    Rcpp::traits::input_parameter< const int& >::type agefirst(agefirstSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type c_hist(c_histSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type isalive(isaliveSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type b_success(b_successSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_moveout(p_moveoutSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_movein(p_moveinSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const int& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_one_indiv_rng(N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, sex, first_cap, first_state, agefirst, c_hist, isalive, b_success, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, ind, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_multi_indivs_rng
Eigen::Matrix<stan::promote_args_t<double, double, double, double, double,                 stan::promote_args_t<double, double, double, double, double,                   stan::promote_args_t<double>>>,-1,-1> states_multi_indivs_rng(const std::vector<int>& INDS, const int& N_INDS, const int& N_STATES_L, const int& N_STATES_O, const int& MAX_T, const std::vector<int>& NO_VISIT, const std::vector<int>& SEX, const std::vector<int>& FIRST_CAP, const std::vector<int>& FIRST_STATE, const std::vector<int>& AGEFIRST, const std::vector<std::vector<int>>& C_HIST, const std::vector<std::vector<int>>& ISALIVE, const std::vector<std::vector<int>>& B_SUCCESS, const std::vector<std::vector<double>>& s_ad, const std::vector<double>& s_ado, const std::vector<double>& s_juv, const std::vector<double>& p_moveout, const std::vector<double>& p_movein, const std::vector<std::vector<double>>& p_breeding, const double& age_rec_scale, const double& age_rec_inflection, const double& age_br_scale, const double& age_br_inflection, const std::vector<double>& p_success, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_multi_indivs_rng(SEXP INDSSEXP, SEXP N_INDSSEXP, SEXP N_STATES_LSEXP, SEXP N_STATES_OSEXP, SEXP MAX_TSEXP, SEXP NO_VISITSEXP, SEXP SEXSEXP, SEXP FIRST_CAPSEXP, SEXP FIRST_STATESEXP, SEXP AGEFIRSTSEXP, SEXP C_HISTSEXP, SEXP ISALIVESEXP, SEXP B_SUCCESSSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_moveoutSEXP, SEXP p_moveinSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type INDS(INDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_INDS(N_INDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_O(N_STATES_OSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NO_VISIT(NO_VISITSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_CAP(FIRST_CAPSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type AGEFIRST(AGEFIRSTSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type C_HIST(C_HISTSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type ISALIVE(ISALIVESEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type B_SUCCESS(B_SUCCESSSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_moveout(p_moveoutSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_movein(p_moveinSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_multi_indivs_rng(INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, C_HIST, ISALIVE, B_SUCCESS, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_multi_indivs_mcmc_rng
std::vector<std::vector<std::vector<int>>> states_multi_indivs_mcmc_rng(const std::vector<int>& INDS, const int& N_INDS, const int& N_STATES_L, const int& N_STATES_O, const int& MAX_T, const std::vector<int>& NO_VISIT, const std::vector<int>& SEX, const std::vector<int>& FIRST_CAP, const std::vector<int>& FIRST_STATE, const std::vector<int>& AGEFIRST, const std::vector<std::vector<int>>& C_HIST, const std::vector<std::vector<int>>& ISALIVE, const std::vector<std::vector<int>>& B_SUCCESS, const std::vector<                                      std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<std::vector<double>>& p_moveout, const std::vector<std::vector<double>>& p_movein, const std::vector<                                      std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const int& NSAMPLES, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_multi_indivs_mcmc_rng(SEXP INDSSEXP, SEXP N_INDSSEXP, SEXP N_STATES_LSEXP, SEXP N_STATES_OSEXP, SEXP MAX_TSEXP, SEXP NO_VISITSEXP, SEXP SEXSEXP, SEXP FIRST_CAPSEXP, SEXP FIRST_STATESEXP, SEXP AGEFIRSTSEXP, SEXP C_HISTSEXP, SEXP ISALIVESEXP, SEXP B_SUCCESSSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_moveoutSEXP, SEXP p_moveinSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP NSAMPLESSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type INDS(INDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_INDS(N_INDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_O(N_STATES_OSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NO_VISIT(NO_VISITSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_CAP(FIRST_CAPSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type AGEFIRST(AGEFIRSTSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type C_HIST(C_HISTSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type ISALIVE(ISALIVESEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type B_SUCCESS(B_SUCCESSSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                      std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_moveout(p_moveoutSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_movein(p_moveinSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                      std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const int& >::type NSAMPLES(NSAMPLESSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_multi_indivs_mcmc_rng(INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, C_HIST, ISALIVE, B_SUCCESS, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, NSAMPLES, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_multi_newinds_mcmc_rng
std::vector<std::vector<int>> states_multi_newinds_mcmc_rng(const int& NROWS, const std::vector<int>& NINDS, const int& N_STATES_L, const int& N_STATES_O, const int& MAX_T, const std::vector<int>& SEX, const std::vector<int>& FIRST_CAP, const std::vector<int>& FIRST_STATE, const std::vector<int>& AGEFIRST, const std::vector<int>& SAMPLE, const std::vector<                                       std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<std::vector<double>>& p_moveout, const std::vector<std::vector<double>>& p_movein, const std::vector<                                       std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_multi_newinds_mcmc_rng(SEXP NROWSSEXP, SEXP NINDSSEXP, SEXP N_STATES_LSEXP, SEXP N_STATES_OSEXP, SEXP MAX_TSEXP, SEXP SEXSEXP, SEXP FIRST_CAPSEXP, SEXP FIRST_STATESEXP, SEXP AGEFIRSTSEXP, SEXP SAMPLESEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_moveoutSEXP, SEXP p_moveinSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type NROWS(NROWSSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NINDS(NINDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_O(N_STATES_OSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_CAP(FIRST_CAPSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type AGEFIRST(AGEFIRSTSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SAMPLE(SAMPLESEXP);
    Rcpp::traits::input_parameter< const std::vector<                                       std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_moveout(p_moveoutSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_movein(p_moveinSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                       std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_multi_newinds_mcmc_rng(NROWS, NINDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, SAMPLE, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_one_indiv_in_rng
std::vector<int> states_one_indiv_in_rng(const int& N_STATES_L, const int& N_STATES_O, const int& MAX_T, const int& sex, const int& first_cap, const int& first_state, const int& agefirst, const std::vector<std::vector<double>>& s_ad, const std::vector<double>& s_ado, const std::vector<double>& s_juv, const std::vector<std::vector<double>>& p_breeding, const double& age_rec_scale, const double& age_rec_inflection, const double& age_br_scale, const double& age_br_inflection, const std::vector<double>& p_success, const int& ind, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_one_indiv_in_rng(SEXP N_STATES_LSEXP, SEXP N_STATES_OSEXP, SEXP MAX_TSEXP, SEXP sexSEXP, SEXP first_capSEXP, SEXP first_stateSEXP, SEXP agefirstSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP indSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_O(N_STATES_OSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const int& >::type sex(sexSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_cap(first_capSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_state(first_stateSEXP);
    Rcpp::traits::input_parameter< const int& >::type agefirst(agefirstSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const int& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_one_indiv_in_rng(N_STATES_L, N_STATES_O, MAX_T, sex, first_cap, first_state, agefirst, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, ind, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_multi_indivs_mcmc_in_rng
std::vector<std::vector<std::vector<int>>> states_multi_indivs_mcmc_in_rng(const std::vector<int>& INDS, const int& N_INDS, const int& N_STATES_L, const int& N_STATES_O, const int& MAX_T, const std::vector<int>& SEX, const std::vector<int>& FIRST_CAP, const std::vector<int>& FIRST_STATE, const std::vector<int>& AGEFIRST, const std::vector<                                         std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<                                         std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const int& NSAMPLES, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_multi_indivs_mcmc_in_rng(SEXP INDSSEXP, SEXP N_INDSSEXP, SEXP N_STATES_LSEXP, SEXP N_STATES_OSEXP, SEXP MAX_TSEXP, SEXP SEXSEXP, SEXP FIRST_CAPSEXP, SEXP FIRST_STATESEXP, SEXP AGEFIRSTSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP NSAMPLESSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type INDS(INDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_INDS(N_INDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_O(N_STATES_OSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_CAP(FIRST_CAPSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type AGEFIRST(AGEFIRSTSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                         std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                         std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const int& >::type NSAMPLES(NSAMPLESSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_multi_indivs_mcmc_in_rng(INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, NSAMPLES, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_multi_newinds_mcmc_in_rng
std::vector<std::vector<int>> states_multi_newinds_mcmc_in_rng(const int& NROWS, const std::vector<int>& NINDS, const int& N_STATES_L, const int& N_STATES_O, const int& MAX_T, const std::vector<int>& SEX, const std::vector<int>& FIRST_CAP, const std::vector<int>& FIRST_STATE, const std::vector<int>& AGEFIRST, const std::vector<int>& SAMPLE, const std::vector<                                          std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<                                          std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_multi_newinds_mcmc_in_rng(SEXP NROWSSEXP, SEXP NINDSSEXP, SEXP N_STATES_LSEXP, SEXP N_STATES_OSEXP, SEXP MAX_TSEXP, SEXP SEXSEXP, SEXP FIRST_CAPSEXP, SEXP FIRST_STATESEXP, SEXP AGEFIRSTSEXP, SEXP SAMPLESEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type NROWS(NROWSSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NINDS(NINDSSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_O(N_STATES_OSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_CAP(FIRST_CAPSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type AGEFIRST(AGEFIRSTSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SAMPLE(SAMPLESEXP);
    Rcpp::traits::input_parameter< const std::vector<                                          std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                          std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_multi_newinds_mcmc_in_rng(NROWS, NINDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, SAMPLE, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_full_from_init0_rng
std::vector<std::vector<std::vector<int>>> states_full_from_init0_rng(const int& NROWS, const int& MAX_T, const int& NSAMPLES, const std::vector<int>& FIRST_STATE, const std::vector<int>& SEX, const std::vector<int>& FIRST_AGE, const std::vector<int>& NINDS, const std::vector<                                    std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<                                    std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const std::vector<double>& p_female, const int& N_STATES_L, const int& BUFFEREDROWS, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_full_from_init0_rng(SEXP NROWSSEXP, SEXP MAX_TSEXP, SEXP NSAMPLESSEXP, SEXP FIRST_STATESEXP, SEXP SEXSEXP, SEXP FIRST_AGESEXP, SEXP NINDSSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP p_femaleSEXP, SEXP N_STATES_LSEXP, SEXP BUFFEREDROWSSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type NROWS(NROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const int& >::type NSAMPLES(NSAMPLESSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_AGE(FIRST_AGESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NINDS(NINDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_female(p_femaleSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type BUFFEREDROWS(BUFFEREDROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_full_from_init0_rng(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_full_from_init_rng
std::vector<std::vector<int>> states_full_from_init_rng(const int& NROWS, const int& MAX_T, const int& NSAMPLES, const std::vector<int>& FIRST_STATE, const std::vector<int>& SEX, const std::vector<int>& FIRST_AGE, const std::vector<int>& NINDS, const std::vector<std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const std::vector<double>& p_female, const int& N_STATES_L, const int& BUFFEREDROWS, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_full_from_init_rng(SEXP NROWSSEXP, SEXP MAX_TSEXP, SEXP NSAMPLESSEXP, SEXP FIRST_STATESEXP, SEXP SEXSEXP, SEXP FIRST_AGESEXP, SEXP NINDSSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP p_femaleSEXP, SEXP N_STATES_LSEXP, SEXP BUFFEREDROWSSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type NROWS(NROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const int& >::type NSAMPLES(NSAMPLESSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_AGE(FIRST_AGESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NINDS(NINDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_female(p_femaleSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type BUFFEREDROWS(BUFFEREDROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_full_from_init_rng(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_full_from_init2_rng
Eigen::Matrix<stan::promote_args_t<double, double, double, double, double,                 stan::promote_args_t<double, double, double, double, double>>,-1,-1> states_full_from_init2_rng(const int& NROWS, const int& MAX_T, const int& NSAMPLES, const std::vector<int>& FIRST_STATE, const std::vector<int>& SEX, const std::vector<int>& FIRST_AGE, const std::vector<int>& NINDS, const std::vector<                                    std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<                                    std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const std::vector<double>& p_female, const int& N_STATES_L, const int& BUFFEREDROWS, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_full_from_init2_rng(SEXP NROWSSEXP, SEXP MAX_TSEXP, SEXP NSAMPLESSEXP, SEXP FIRST_STATESEXP, SEXP SEXSEXP, SEXP FIRST_AGESEXP, SEXP NINDSSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP p_femaleSEXP, SEXP N_STATES_LSEXP, SEXP BUFFEREDROWSSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type NROWS(NROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const int& >::type NSAMPLES(NSAMPLESSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_AGE(FIRST_AGESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NINDS(NINDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_female(p_femaleSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type BUFFEREDROWS(BUFFEREDROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_full_from_init2_rng(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_full_from_init3_rng
std::vector<std::vector<int>> states_full_from_init3_rng(const int& NROWS, const int& MAX_T, const int& NSAMPLES, const std::vector<int>& FIRST_STATE, const std::vector<int>& SEX, const std::vector<int>& FIRST_AGE, const std::vector<int>& NINDS, const std::vector<                                    std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<                                    std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const std::vector<double>& p_female, const int& N_STATES_L, const int& BUFFEREDROWS, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_full_from_init3_rng(SEXP NROWSSEXP, SEXP MAX_TSEXP, SEXP NSAMPLESSEXP, SEXP FIRST_STATESEXP, SEXP SEXSEXP, SEXP FIRST_AGESEXP, SEXP NINDSSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP p_femaleSEXP, SEXP N_STATES_LSEXP, SEXP BUFFEREDROWSSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type NROWS(NROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const int& >::type NSAMPLES(NSAMPLESSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_AGE(FIRST_AGESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NINDS(NINDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_female(p_femaleSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type BUFFEREDROWS(BUFFEREDROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_full_from_init3_rng(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}
// states_full_from_init4_rng
std::vector<std::vector<int>> states_full_from_init4_rng(const int& NROWS, const int& MAX_T, const int& NSAMPLES, const std::vector<int>& FIRST_STATE, const std::vector<int>& SEX, const std::vector<int>& FIRST_AGE, const std::vector<int>& NINDS, const std::vector<                                    std::vector<std::vector<double>>>& s_ad, const std::vector<std::vector<double>>& s_ado, const std::vector<std::vector<double>>& s_juv, const std::vector<                                    std::vector<std::vector<double>>>& p_breeding, const std::vector<double>& age_rec_scale, const std::vector<double>& age_rec_inflection, const std::vector<double>& age_br_scale, const std::vector<double>& age_br_inflection, const std::vector<std::vector<double>>& p_success, const std::vector<double>& p_female, const int& N_STATES_L, const int& BUFFEREDROWS, const int& debug, boost::ecuyer1988& base_rng__, std::ostream* pstream__);
RcppExport SEXP _gibsonsfuns_states_full_from_init4_rng(SEXP NROWSSEXP, SEXP MAX_TSEXP, SEXP NSAMPLESSEXP, SEXP FIRST_STATESEXP, SEXP SEXSEXP, SEXP FIRST_AGESEXP, SEXP NINDSSEXP, SEXP s_adSEXP, SEXP s_adoSEXP, SEXP s_juvSEXP, SEXP p_breedingSEXP, SEXP age_rec_scaleSEXP, SEXP age_rec_inflectionSEXP, SEXP age_br_scaleSEXP, SEXP age_br_inflectionSEXP, SEXP p_successSEXP, SEXP p_femaleSEXP, SEXP N_STATES_LSEXP, SEXP BUFFEREDROWSSEXP, SEXP debugSEXP, SEXP base_rng__SEXP, SEXP pstream__SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type NROWS(NROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type MAX_T(MAX_TSEXP);
    Rcpp::traits::input_parameter< const int& >::type NSAMPLES(NSAMPLESSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_STATE(FIRST_STATESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type SEX(SEXSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type FIRST_AGE(FIRST_AGESEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type NINDS(NINDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type s_ad(s_adSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_ado(s_adoSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type s_juv(s_juvSEXP);
    Rcpp::traits::input_parameter< const std::vector<                                    std::vector<std::vector<double>>>& >::type p_breeding(p_breedingSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_scale(age_rec_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_rec_inflection(age_rec_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_scale(age_br_scaleSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type age_br_inflection(age_br_inflectionSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type p_success(p_successSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type p_female(p_femaleSEXP);
    Rcpp::traits::input_parameter< const int& >::type N_STATES_L(N_STATES_LSEXP);
    Rcpp::traits::input_parameter< const int& >::type BUFFEREDROWS(BUFFEREDROWSSEXP);
    Rcpp::traits::input_parameter< const int& >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< boost::ecuyer1988& >::type base_rng__(base_rng__SEXP);
    Rcpp::traits::input_parameter< std::ostream* >::type pstream__(pstream__SEXP);
    rcpp_result_gen = Rcpp::wrap(states_full_from_init4_rng(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gibsonsfuns_trans_probs1", (DL_FUNC) &_gibsonsfuns_trans_probs1, 13},
    {"_gibsonsfuns_obs_probs1", (DL_FUNC) &_gibsonsfuns_obs_probs1, 10},
    {"_gibsonsfuns_states_one_indiv_rng", (DL_FUNC) &_gibsonsfuns_states_one_indiv_rng, 26},
    {"_gibsonsfuns_states_multi_indivs_rng", (DL_FUNC) &_gibsonsfuns_states_multi_indivs_rng, 27},
    {"_gibsonsfuns_states_multi_indivs_mcmc_rng", (DL_FUNC) &_gibsonsfuns_states_multi_indivs_mcmc_rng, 28},
    {"_gibsonsfuns_states_multi_newinds_mcmc_rng", (DL_FUNC) &_gibsonsfuns_states_multi_newinds_mcmc_rng, 24},
    {"_gibsonsfuns_states_one_indiv_in_rng", (DL_FUNC) &_gibsonsfuns_states_one_indiv_in_rng, 20},
    {"_gibsonsfuns_states_multi_indivs_mcmc_in_rng", (DL_FUNC) &_gibsonsfuns_states_multi_indivs_mcmc_in_rng, 22},
    {"_gibsonsfuns_states_multi_newinds_mcmc_in_rng", (DL_FUNC) &_gibsonsfuns_states_multi_newinds_mcmc_in_rng, 22},
    {"_gibsonsfuns_states_full_from_init0_rng", (DL_FUNC) &_gibsonsfuns_states_full_from_init0_rng, 22},
    {"_gibsonsfuns_states_full_from_init_rng", (DL_FUNC) &_gibsonsfuns_states_full_from_init_rng, 22},
    {"_gibsonsfuns_states_full_from_init2_rng", (DL_FUNC) &_gibsonsfuns_states_full_from_init2_rng, 22},
    {"_gibsonsfuns_states_full_from_init3_rng", (DL_FUNC) &_gibsonsfuns_states_full_from_init3_rng, 22},
    {"_gibsonsfuns_states_full_from_init4_rng", (DL_FUNC) &_gibsonsfuns_states_full_from_init4_rng, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_gibsonsfuns(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
