# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trans_probs1 <- function(instate, nstates, s_ad, s_ado, s_juv, p_mv_out, p_mv_in, succ, p_breed, p_rec, p_bead, p_succ, pstream__ = 0L) {
    .Call(`_gibsonsfuns_trans_probs1`, instate, nstates, s_ad, s_ado, s_juv, p_mv_out, p_mv_in, succ, p_breed, p_rec, p_bead, p_succ, pstream__)
}

obs_probs1 <- function(latstate, n_obs_states, p_obs, p_detect_juv, p_detect_dead, p_female, p_succ, succ, no_visit, pstream__ = 0L) {
    .Call(`_gibsonsfuns_obs_probs1`, latstate, n_obs_states, p_obs, p_detect_juv, p_detect_dead, p_female, p_succ, succ, no_visit, pstream__)
}

states_one_indiv_rng <- function(N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, sex, first_cap, first_state, agefirst, c_hist, isalive, b_success, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, ind, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_one_indiv_rng`, N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, sex, first_cap, first_state, agefirst, c_hist, isalive, b_success, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, ind, debug, base_rng__, pstream__)
}

states_multi_indivs_rng <- function(INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, C_HIST, ISALIVE, B_SUCCESS, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_multi_indivs_rng`, INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, C_HIST, ISALIVE, B_SUCCESS, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__)
}

states_multi_indivs_mcmc_rng <- function(INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, C_HIST, ISALIVE, B_SUCCESS, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, NSAMPLES, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_multi_indivs_mcmc_rng`, INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, NO_VISIT, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, C_HIST, ISALIVE, B_SUCCESS, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, NSAMPLES, debug, base_rng__, pstream__)
}

states_multi_newinds_mcmc_rng <- function(NROWS, NINDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, SAMPLE, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_multi_newinds_mcmc_rng`, NROWS, NINDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, SAMPLE, s_ad, s_ado, s_juv, p_moveout, p_movein, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__)
}

states_one_indiv_in_rng <- function(N_STATES_L, N_STATES_O, MAX_T, sex, first_cap, first_state, agefirst, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, ind, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_one_indiv_in_rng`, N_STATES_L, N_STATES_O, MAX_T, sex, first_cap, first_state, agefirst, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, ind, debug, base_rng__, pstream__)
}

states_multi_indivs_mcmc_in_rng <- function(INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, NSAMPLES, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_multi_indivs_mcmc_in_rng`, INDS, N_INDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, NSAMPLES, debug, base_rng__, pstream__)
}

states_multi_newinds_mcmc_in_rng <- function(NROWS, NINDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, SAMPLE, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_multi_newinds_mcmc_in_rng`, NROWS, NINDS, N_STATES_L, N_STATES_O, MAX_T, SEX, FIRST_CAP, FIRST_STATE, AGEFIRST, SAMPLE, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, debug, base_rng__, pstream__)
}

states_full_from_init0_rng <- function(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_full_from_init0_rng`, NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__)
}

states_full_from_init_rng <- function(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_full_from_init_rng`, NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__)
}

states_full_from_init2_rng <- function(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_full_from_init2_rng`, NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__)
}

states_full_from_init3_rng <- function(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_full_from_init3_rng`, NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__)
}

states_full_from_init4_rng <- function(NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__ = 0L) {
    .Call(`_gibsonsfuns_states_full_from_init4_rng`, NROWS, MAX_T, NSAMPLES, FIRST_STATE, SEX, FIRST_AGE, NINDS, s_ad, s_ado, s_juv, p_breeding, age_rec_scale, age_rec_inflection, age_br_scale, age_br_inflection, p_success, p_female, N_STATES_L, BUFFEREDROWS, debug, base_rng__, pstream__)
}

